// Chapter 26 (Rounding Numbers)

// 1. Form a statement that rounds a number to the nearest integer.

// var a=3.6;
// console.log(Math.floor(a));

/*
2. Round up a number represented by origNum and assign it to 
roundNum, which hasn't been declared beforehand.
// */
// var origNum=4.7;
// var newNum=Math.round(origNum);
// console.log(newNum);


/*
3. Round down a number represented by origNum and assign it to 
roundNum, which hasn't been declared beforehand
*/
// var a=2.9;
// var b=Math.floor(a);
// console.log(b);


/*
4. Round a number represented by a variable and assign the result 
to a second variable that hasn't been declared beforehand
*/
// var a=5.1;
// var b=Math.ceil(a);
// console.log(b);

/*
5. Round .5 to 0 and assign it to a variable that hasn't been declared 
beforehand
*/
// var a=0.5;
// var b=Math.floor(a);
// console.log(b);



// Chapter 27 (Random Numbers)

/*
1. Convert a random number generated by JavaScript to a number in 
the range 1 to 50

*/

// var a=Math.random()* 50;
// var b=Math.ceil(a);
// console.log(b);



/*
. Generate a random number and assign it to a variable that hasn't 
been declared beforehand.
*/
// var a=Math.random();
// console.log(a);


/*
3. You have to create a dice in JavaScript with the use of pseud random number.
*/

// var a=Math.ceil(Math.random()*6);
// console.log(a);


/*
4. You have to create a toss (head/tail) in JavaScript with the use of 
pseudo-random number.
*/

// var HeadsUserName=prompt('Enter Heads User Name','Noman Khan');
// var TailsUserName=prompt('Enter Tail User Name','Faizan Abid');

// var Random_=Math.ceil(Math.random()*2);
// if(Random_==1){
//     console.log(`${HeadsUserName} win the game`);
//     console.log(Random_);
// }
// else{
//     {
//         console.log(`${TailsUserName} win the Game`);
//         console.log(Random_);
//     }
// }


// Chapter 28, 29 (Converting Strings)

/*
1. How do you convert a string to an integer in JavaScript?
*/
// var abc='123';
// console.log(typeof abc);
// abc=parseInt(abc)
// console.log(typeof abc)

/*
2. Write a JavaScript function to convert the string "123" to an 
integer.
*/
// var a="123";
// console.log(typeof a);
// a=parseInt(a)
// console.log(typeof a);


/*
3. How can you convert a string containing a decimal number to a 
floating-point number in JavaScript?
*/
// var abc='3.142';
// var pi=parseFloat(abc);
// console.log(typeof pi);

/*
4. How can you check if a string can be successfully converted to an 
integer or decimal in JavaScript before performing the 
conversion?
*/

// type of method 


/*
5. How can you convert a number to a string in JavaScript?
*/
// var a=3.142;
// console.log(typeof a);
// a=toString(a);
// console.log(typeof a);

/*
6. Write a JavaScript function to convert the number 42 to a string.
*/
// var fu=42;
// console.log(typeof fu);
// fu=toString(fu);
// console.log(typeof fu);

/*
7. Can you convert a string representing a decimal number (e.g., 
    "3.14") to an integer in JavaScript? If so, how?
    */

    // var pi=3.14;
    // console.log(parseInt(pi));


   /* Chapter 30 (Controlling the length of 
        decimals) */

        /*
        1. Code a statement that rounds a number represented by num to 4 
places, converts it to a string, and assigns it to newNum, which 
hasn't been declared beforehand.
*/
// var a=4.2344545;
// var b=toString(a.toFixed(4));
// console.log(typeof b + ` ${b}`);


/*
2. In a single statement round a number represented by a variable to 
2 places, convert it to a string, convert it back to a number, and 
assign it to the same variable.
*/
// var a=3.14;
// a=toString(a);
// a=Number(a);
// console.log(typeof a);

/*
3. Code the first line of an if statement that tests whether the 
number represented by num, rounded to 2 digits and converted 
to a string, has more than 4 characters in it.
*/















/*
4. Assign a number with many decimal places to a variable.
Code an alert that displays the number rounded to 2 decimal 
places and converted to a string.
*/
// var a=1.1243435
// alert(a.toFixed(2));